const SIZE=8,GOAL0=100,GOAL_STEP=35,TOTAL_TIME=120,BAD_SWAP_PENALTY=2,SWIPE=18,MAX_FLIGHTS=12;
const FRUITS=[['apple','Apple','🍎',1],['banana','Banana','🍌',1],['grape','Grape','🍇',1],['orange','Orange','🍊',1],['strawberry','Strawberry','🍓',1],['watermelon','Watermelon','🍉',2],['pear','Pear','🍐',3],['peach','Peach','🍑',4]].map(([type,label,emoji,unlock])=>({type,label,emoji,unlock}));
const LOOKUP=Object.fromEntries(FRUITS.map(f=>[f.type,f]));
const $=id=>document.getElementById(id);
const el={board:$('board'),shell:document.querySelector('.board-shell'),level:$('level-value'),time:$('time-value'),timer:$('timer-pill'),score:$('score-value'),bombs:$('bomb-value'),meter:$('meter-label'),meterFill:$('meter-fill'),meterTop:$('meter-inline-label'),meterTopFill:$('meter-inline-fill'),meterTrack:document.querySelector('.meter-track'),meterTopTrack:document.querySelector('.inline-meter-track'),hint:$('unlock-text'),newBtn:$('new-game-button'),overlay:$('board-overlay'),overlayEyebrow:$('overlay-eyebrow'),overlayTitle:$('overlay-title'),overlayText:$('overlay-text'),overlayBtn:$('continue-button')};
const fx=document.createElement('div');fx.className='fx-layer';document.body.appendChild(fx);
const state={board:[],level:1,score:0,bombs:0,meter:0,goal:GOAL0,time:TOTAL_TIME,timer:null,busy:false,pending:false,expired:false,overlay:null,swipe:null,fruits:[]};
const key=(r,c)=>`${r},${c}`,coords=k=>k.split(',').map(Number),inBounds=(r,c)=>r>=0&&r<SIZE&&c>=0&&c<SIZE,wait=ms=>new Promise(r=>setTimeout(r,ms));
const formatTime=t=>`${Math.floor(t/60)}:${String(t%60).padStart(2,'0')}`;
const nextFruit=l=>FRUITS.find(f=>f.unlock>l)||null,activeFruits=l=>FRUITS.filter(f=>f.unlock<=l),bombChance=()=>Math.min(.05+(state.level-1)*.015,.16);
function randFruit(){const f=state.fruits[Math.floor(Math.random()*state.fruits.length)];return{kind:'fruit',type:f.type};}
function randPiece(){return Math.random()<bombChance()?{kind:'bomb'}:randFruit();}
function countDir(b,r,c,dr,dc,type){let n=0;r+=dr;c+=dc;while(inBounds(r,c)){const p=b[r][c];if(!p||p.kind!=='fruit'||p.type!==type)break;n++;r+=dr;c+=dc;}return n;}
function makesRun(b,r,c,p){if(!p||p.kind!=='fruit')return false;return 1+countDir(b,r,c,0,-1,p.type)+countDir(b,r,c,0,1,p.type)>=3||1+countDir(b,r,c,-1,0,p.type)+countDir(b,r,c,1,0,p.type)>=3;}
function newBoard(){const b=Array.from({length:SIZE},()=>Array(SIZE).fill(null));for(let r=0;r<SIZE;r++)for(let c=0;c<SIZE;c++){let p=randPiece(),safe=0;while(makesRun(b,r,c,p)&&safe<20){p=randPiece();safe++;}b[r][c]=p;}return b;}
function findMatches(b){const out=new Set();for(let r=0;r<SIZE;r++){let c=0;while(c<SIZE){const p=b[r][c];if(!p||p.kind!=='fruit'){c++;continue;}let e=c+1;while(e<SIZE&&b[r][e]&&b[r][e].kind==='fruit'&&b[r][e].type===p.type)e++;if(e-c>=3)for(let i=c;i<e;i++)out.add(key(r,i));c=e;}}for(let c=0;c<SIZE;c++){let r=0;while(r<SIZE){const p=b[r][c];if(!p||p.kind!=='fruit'){r++;continue;}let e=r+1;while(e<SIZE&&b[e][c]&&b[e][c].kind==='fruit'&&b[e][c].type===p.type)e++;if(e-r>=3)for(let i=r;i<e;i++)out.add(key(i,c));r=e;}}return out;}
function adjacentBombs(matchSet){const out=[],seen=new Set();for(const k0 of matchSet){const[r,c]=coords(k0);for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){if(!dr&&!dc)continue;const nr=r+dr,nc=c+dc,k1=key(nr,nc);if(!inBounds(nr,nc)||seen.has(k1))continue;const p=state.board[nr][nc];if(p&&p.kind==='bomb'){seen.add(k1);out.push([nr,nc]);}}}return out;}
function tile(r,c){return el.board.querySelector(`.tile[data-row="${r}"][data-col="${c}"]`);} 
function sample(xs){if(xs.length<=MAX_FLIGHTS)return xs;const out=[],step=xs.length/MAX_FLIGHTS;for(let i=0;i<MAX_FLIGHTS;i++)out.push(xs[Math.floor(i*step)]);return out;}
function badgeInfo(cleared,text,variant){if(!text)return null;const pts=[];for(const k0 of cleared){const[r,c]=coords(k0),t=tile(r,c);if(!t)continue;const box=t.getBoundingClientRect();pts.push([box.left+box.width/2,box.top+box.height/2]);}const box=el.board.getBoundingClientRect(),x=pts.length?pts.reduce((s,p)=>s+p[0],0)/pts.length:box.left+box.width/2,y=pts.length?pts.reduce((s,p)=>s+p[1],0)/pts.length:box.top+box.height/2;return{x,y,text,variant};}
function fruitFlights(cands){const track=el.meterTopTrack;if(!track)return[];const mr=track.getBoundingClientRect();return sample(cands).map((cand,i)=>{const t=tile(cand.row,cand.col);if(!t)return null;const tr=t.getBoundingClientRect();const tx=mr.left+Math.min(mr.width-18,18+(i/Math.max(sample(cands).length-1,1))*Math.max(mr.width-36,0));return{emoji:LOOKUP[cand.type].emoji,startX:tr.left+tr.width/2,startY:tr.top+tr.height/2,endX:tx,endY:mr.top+mr.height/2,size:Math.max(22,Math.min(tr.width*.72,38))};}).filter(Boolean);}
function animateBadge(info,className,rise=90,dur=850){if(!info)return Promise.resolve();return new Promise(done=>{const n=document.createElement('div');n.className=className;n.textContent=info.text;fx.appendChild(n);const a=n.animate([{transform:`translate(${info.x-38}px, ${info.y-16}px) scale(.8)`,opacity:0},{transform:`translate(${info.x-38}px, ${info.y-44}px) scale(1.06)`,opacity:1,offset:.28},{transform:`translate(${info.x-38}px, ${info.y-rise}px) scale(1)`,opacity:0}],{duration:dur,easing:'cubic-bezier(0.18, 0.84, 0.32, 1)',fill:'forwards'});a.onfinish=()=>{n.remove();done();};});}
function animateScore(info){return animateBadge(info,`score-pop score-pop--${info?.variant||'fruit'}`,96,820);} function animateCombo(info){return animateBadge(info,'combo-pop',122,920);} 
async function animateFlights(flights){if(!flights.length)return;el.meterTopTrack?.classList.add('is-pulsing');el.meterTrack?.classList.add('is-pulsing');await Promise.all(flights.map((f,i)=>new Promise(done=>{const n=document.createElement('div');n.className='flying-fruit';n.textContent=f.emoji;n.style.width=`${f.size}px`;n.style.height=`${f.size}px`;n.style.fontSize=`${f.size*.78}px`;fx.appendChild(n);const ay=Math.min(f.startY,f.endY)-(48+Math.random()*28),mx=(f.startX+f.endX)/2+(Math.random()*32-16),a=n.animate([{transform:`translate(${f.startX-f.size/2}px, ${f.startY-f.size/2}px) scale(1) rotate(0deg)`,opacity:1},{transform:`translate(${mx-f.size/2}px, ${ay-f.size/2}px) scale(1.15) rotate(${Math.random()*20-10}deg)`,opacity:1,offset:.45},{transform:`translate(${f.endX-f.size/2}px, ${f.endY-f.size/2}px) scale(.28) rotate(${Math.random()*40-20}deg)`,opacity:.18}],{duration:560,delay:i*42,easing:'cubic-bezier(0.22, 0.9, 0.31, 1)',fill:'forwards'});a.onfinish=()=>{n.remove();done();};})));el.meterTopTrack?.classList.remove('is-pulsing');el.meterTrack?.classList.remove('is-pulsing');}
async function shake(bombs){if(!el.shell||bombs<=0)return;const q=Math.min(4+bombs*1.5,10);await el.shell.animate([{transform:'translate3d(0,0,0)'},{transform:`translate3d(${q}px,-2px,0)`},{transform:`translate3d(${-q}px,2px,0)`},{transform:`translate3d(${q*.7}px,0,0)`},{transform:`translate3d(${-q*.7}px,0,0)`},{transform:'translate3d(0,0,0)'}],{duration:320,easing:'ease-out'}).finished;}
function buildResolution({matchSet=new Set(),initialBombs=[],combo=1}){const cleared=new Set(matchSet),queue=[...initialBombs],queued=new Set(initialBombs.map(([r,c])=>key(r,c))),done=new Set();for(const bc of adjacentBombs(matchSet)){const k0=key(...bc);if(!queued.has(k0)){queued.add(k0);queue.push(bc);}}while(queue.length){const[br,bc]=queue.shift(),k0=key(br,bc),bomb=state.board[br]?.[bc];if(done.has(k0)||!bomb||bomb.kind!=='bomb')continue;done.add(k0);cleared.add(k0);for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){const nr=br+dr,nc=bc+dc,k1=key(nr,nc);if(!inBounds(nr,nc))continue;const p=state.board[nr][nc];cleared.add(k1);if(p&&p.kind==='bomb'&&!queued.has(k1)){queued.add(k1);queue.push([nr,nc]);}}}
let fruits=0,bombs=0;const flyers=[];for(const k0 of cleared){const[r,c]=coords(k0),p=state.board[r][c];if(!p)continue;if(p.kind==='bomb')bombs++;else{fruits++;flyers.push({row:r,col:c,type:p.type});}state.board[r][c]=null;}
const base=fruits*10+bombs*75,scoreGain=base*combo,meterGain=fruits+bombs*12+Math.max(combo-1,0)*2;state.score+=scoreGain;state.bombs+=bombs;state.meter=Math.min(state.goal,state.meter+meterGain);if(state.meter>=state.goal)state.pending=true;return{count:fruits+bombs,bombs,flights:fruitFlights(flyers),score:badgeInfo(cleared,combo>1?`+${scoreGain} x${combo}`:bombs?`+${scoreGain} 💥`:`+${scoreGain}`,bombs?'bomb':'fruit'),combo:combo>1?badgeInfo(cleared,`Combo x${combo}!`,'combo'):null};}
function collapse(){for(let c=0;c<SIZE;c++){let wr=SIZE-1;for(let r=SIZE-1;r>=0;r--)if(state.board[r][c]){state.board[wr][c]=state.board[r][c];if(wr!==r)state.board[r][c]=null;wr--;}while(wr>=0){state.board[wr][c]=null;wr--;}}}
function refill(){for(let r=0;r<SIZE;r++)for(let c=0;c<SIZE;c++)if(!state.board[r][c])state.board[r][c]=randPiece();}
function movedBombs(fr,fc,tr,tc){const out=[],seen=new Set();for(const[r,c]of[[fr,fc],[tr,tc]]){const p=state.board[r][c],k0=key(r,c);if(p&&p.kind==='bomb'&&!seen.has(k0)){seen.add(k0);out.push([r,c]);}}return out;}
function renderBoard(){el.board.innerHTML='';for(let r=0;r<SIZE;r++)for(let c=0;c<SIZE;c++){const p=state.board[r][c],b=document.createElement('button');b.type='button';b.dataset.row=String(r);b.dataset.col=String(c);if(!p){b.className='tile tile--empty';b.disabled=true;b.setAttribute('aria-hidden','true');el.board.appendChild(b);continue;}b.className=`tile tile--${p.kind==='bomb'?'bomb':p.type}`;b.setAttribute('aria-label',p.kind==='bomb'?`Bomb at row ${r+1}, column ${c+1}`:`${LOOKUP[p.type].label} at row ${r+1}, column ${c+1}`);if(state.swipe&&state.swipe.row===r&&state.swipe.col===c)b.classList.add('is-active');const inner=document.createElement('span');inner.className='tile-inner';const piece=document.createElement('span');piece.className='piece';piece.textContent=p.kind==='bomb'?'💣':LOOKUP[p.type].emoji;inner.appendChild(piece);b.appendChild(inner);el.board.appendChild(b);}}
function render(){renderBoard();const txt=`${state.meter} / ${state.goal}`,pct=`${(state.meter/state.goal)*100}%`;el.level.textContent=String(state.level);el.time.textContent=formatTime(state.time);el.timer.classList.remove('is-warning','is-danger');if(state.time<=15)el.timer.classList.add('is-danger');else if(state.time<=30)el.timer.classList.add('is-warning');el.score.textContent=String(state.score);el.bombs.textContent=String(state.bombs);el.meter.textContent=txt;el.meterFill.style.width=pct;el.meterTop.textContent=txt;el.meterTopFill.style.width=pct;const nxt=nextFruit(state.level);el.hint.textContent=nxt?`Level ${state.level}: ${state.fruits.length} fruit types active. Next unlock: ${nxt.label} at level ${nxt.unlock}. Goal pressure rises every level.`:'All current fruit are unlocked. Bomb chance and meter pressure keep ramping up as you climb.';}
function hideOverlay(){state.overlay=null;el.overlay.classList.add('hidden');}
function showLevelOverlay(){const nxt=nextFruit(state.level);state.overlay='level';clearTimer();el.overlayEyebrow.textContent='Level cleared';el.overlayTitle.textContent=`Level ${state.level+1}`;el.overlayText.textContent=nxt&&nxt.unlock===state.level+1?`${nxt.label} joins the board next. Goals get steeper from here.`:'Fresh board, tougher goal, and less room for sloppy swipes.';el.overlayBtn.textContent='Keep Crushing';el.overlay.classList.remove('hidden');}
function showGameOver(){state.overlay='gameover';state.expired=true;state.pending=false;clearTimer();state.busy=false;el.overlayEyebrow.textContent="Time's up";el.overlayTitle.textContent='Round Over';el.overlayText.textContent=`Final score: ${state.score}. You reached level ${state.level}. Tap below to jump back in.`;el.overlayBtn.textContent='Play Again';el.overlay.classList.remove('hidden');}
function tick(){if(state.expired||state.overlay==='gameover')return;state.time=Math.max(0,state.time-1);render();if(state.time===0){clearTimer();state.expired=true;if(!state.busy)showGameOver();}}
function startTimer(reset=false){clearTimer();if(reset)state.time=TOTAL_TIME;render();if(state.time>0&&!state.expired)state.timer=setInterval(tick,1000);} 
async function resolve(initial=null){let pending=initial,chain=1;while(true){let res;if(pending){res=buildResolution({...pending,combo:chain});pending=null;if(!res.count)break;}else{const matches=findMatches(state.board);if(!matches.size)break;res=buildResolution({matchSet:matches,combo:chain});}render();await Promise.all([animateFlights(res.flights),animateScore(res.score),animateCombo(res.combo),shake(res.bombs)]);await wait(120);collapse();refill();render();await wait(170);if(state.expired||state.pending)break;chain++;}state.busy=false;if(state.expired){showGameOver();return;}if(state.pending)showLevelOverlay();}
async function trySwap(fr,fc,tr,tc){if(!inBounds(tr,tc)||state.busy||state.pending||state.expired||state.overlay==='gameover')return;state.busy=true;[state.board[fr][fc],state.board[tr][tc]]=[state.board[tr][tc],state.board[fr][fc]];renderBoard();await wait(120);const mb=movedBombs(fr,fc,tr,tc);if(mb.length){await resolve({initialBombs:mb});return;}const matches=findMatches(state.board);if(!matches.size){[state.board[fr][fc],state.board[tr][tc]]=[state.board[tr][tc],state.board[fr][fc]];renderBoard();await wait(120);applyTimePenalty(BAD_SWAP_PENALTY);state.busy=false;return;}await resolve({matchSet:matches});}
function startRun(){clearTimer();Object.assign(state,{level:1,score:0,bombs:0,meter:0,goal:GOAL0,time:TOTAL_TIME,busy:false,pending:false,expired:false,overlay:null,swipe:null});state.fruits=activeFruits(state.level);state.board=newBoard();hideOverlay();render();startTimer(false);} 
function nextLevel(){if(state.expired){showGameOver();return;}state.level++;state.goal=GOAL0+(state.level-1)*GOAL_STEP;state.meter=0;state.pending=false;state.fruits=activeFruits(state.level);state.board=newBoard();hideOverlay();render();startTimer(false);} 
function overlayAction(){if(state.overlay==='gameover')startRun();else if(state.overlay==='level')nextLevel();}
function down(e){const t=e.target.closest('.tile');if(!t||state.busy||state.pending||state.expired||t.disabled)return;state.swipe={row:Number(t.dataset.row),col:Number(t.dataset.col),x:e.clientX,y:e.clientY,id:e.pointerId};el.board.setPointerCapture(e.pointerId);renderBoard();}
function release(id){if(el.board.hasPointerCapture(id))el.board.releasePointerCapture(id);} 
function up(e){if(!state.swipe||e.pointerId!==state.swipe.id)return;const{row,col,x,y}=state.swipe;release(e.pointerId);state.swipe=null;const dx=e.clientX-x,dy=e.clientY-y;renderBoard();if(Math.hypot(dx,dy)<SWIPE)return;let nr=row,nc=col;if(Math.abs(dx)>Math.abs(dy))nc+=dx>0?1:-1;else nr+=dy>0?1:-1;trySwap(row,col,nr,nc);} 
function cancel(e){if(!state.swipe||e.pointerId!==state.swipe.id)return;release(e.pointerId);state.swipe=null;renderBoard();}
el.board.addEventListener('pointerdown',down);el.board.addEventListener('pointerup',up);el.board.addEventListener('pointercancel',cancel);el.newBtn.addEventListener('click',startRun);el.overlayBtn.addEventListener('click',overlayAction);startRun();