const BOARD_SIZE=8,LEVEL_GOAL_START=100,LEVEL_GOAL_STEP=35,ROUND_TIME_SECONDS=120,TIME_BONUS_CAP=180,INVALID_SWAP_PENALTY=2,SWIPE_THRESHOLD=18,BOMB_BANK_MAX=5;
const FRUITS=[['apple','Apple','🍎',1],['banana','Banana','🍌',1],['grape','Grape','🍇',1],['orange','Orange','🍊',1],['strawberry','Strawberry','🍓',1],['watermelon','Watermelon','🍉',2],['pear','Pear','🍐',3],['peach','Peach','🍑',4]].map(([type,label,emoji,unlockLevel])=>({type,label,emoji,unlockLevel}));
const LOOKUP=Object.fromEntries(FRUITS.map(f=>[f.type,f]));
const $=id=>document.getElementById(id);
const boardElement=$('board'),boardShell=document.querySelector('.board-shell'),levelEl=$('level-value'),timeEl=$('time-value'),timerEl=$('timer-pill'),scoreEl=$('score-value'),bombsEl=$('bomb-value'),bankEl=$('bomb-bank-value'),bankBtn=$('bomb-bank-button'),meterEl=$('meter-label'),meterFill=$('meter-fill'),meterTop=$('meter-inline-label'),meterTopFill=$('meter-inline-fill'),hintEl=$('unlock-text'),newBtn=$('new-game-button'),overlay=$('board-overlay'),overlayEyebrow=$('overlay-eyebrow'),overlayTitle=$('overlay-title'),overlayText=$('overlay-text'),continueBtn=$('continue-button');
const fx=document.createElement('div');fx.className='fx-layer';document.body.appendChild(fx);
const state={board:[],level:1,score:0,bombsDetonated:0,bombBank:0,meter:0,meterGoal:LEVEL_GOAL_START,timeLeft:ROUND_TIME_SECONDS,timerId:null,busy:false,pendingLevelUp:false,timeExpired:false,overlayMode:null,availableFruits:[],swipeStart:null};
const key=(r,c)=>`${r},${c}`,coords=k=>k.split(',').map(Number),inside=(r,c)=>r>=0&&r<BOARD_SIZE&&c>=0&&c<BOARD_SIZE,wait=ms=>new Promise(r=>setTimeout(r,ms));
function fmt(t){return `${Math.floor(t/60)}:${String(t%60).padStart(2,'0')}`}
function clearTimer(){if(state.timerId){clearInterval(state.timerId);state.timerId=null}}
function tick(){if(state.timeExpired||state.overlayMode==='gameover')return;state.timeLeft=Math.max(0,state.timeLeft-1);renderHud();if(state.timeLeft===0){clearTimer();state.timeExpired=true;if(!state.busy)showGameOver()}}
function startTimer(reset=false){clearTimer();if(reset)state.timeLeft=ROUND_TIME_SECONDS;renderHud();if(state.timeLeft>0&&!state.timeExpired)state.timerId=setInterval(tick,1000)}
function addTime(n){if(!state.timeExpired)state.timeLeft=Math.min(TIME_BONUS_CAP,state.timeLeft+n)}
function penalty(n){if(state.timeExpired)return;state.timeLeft=Math.max(0,state.timeLeft-n);renderHud();if(state.timeLeft===0){clearTimer();state.timeExpired=true;if(!state.busy)showGameOver()}}
function activeFruits(){return FRUITS.filter(f=>f.unlockLevel<=state.level)}
function nextFruit(){return FRUITS.find(f=>f.unlockLevel>state.level)||null}
function randomFruit(){const f=state.availableFruits[Math.floor(Math.random()*state.availableFruits.length)];return{kind:'fruit',type:f.type}}
function countDir(board,r,c,dr,dc,type){let n=0;r+=dr;c+=dc;while(inside(r,c)){const p=board[r][c];if(!p||p.kind!=='fruit'||p.type!==type)break;n++;r+=dr;c+=dc}return n}
function makesRun(board,r,c,p){if(!p||p.kind!=='fruit')return false;return 1+countDir(board,r,c,0,-1,p.type)+countDir(board,r,c,0,1,p.type)>=3||1+countDir(board,r,c,-1,0,p.type)+countDir(board,r,c,1,0,p.type)>=3}
function makeBoard(){const b=Array.from({length:BOARD_SIZE},()=>Array(BOARD_SIZE).fill(null));for(let r=0;r<BOARD_SIZE;r++)for(let c=0;c<BOARD_SIZE;c++){let p=randomFruit(),guard=0;while(makesRun(b,r,c,p)&&guard<30){p=randomFruit();guard++}b[r][c]=p}return b}
function scanMatches(){const matched=new Set();let earned=0;for(let r=0;r<BOARD_SIZE;r++){let c=0;while(c<BOARD_SIZE){const p=state.board[r][c];if(!p||p.kind!=='fruit'){c++;continue}let end=c+1;while(end<BOARD_SIZE&&state.board[r][end]&&state.board[r][end].kind==='fruit'&&state.board[r][end].type===p.type)end++;if(end-c>=3){for(let i=c;i<end;i++)matched.add(key(r,i));if(end-c>=5)earned++}c=end}}for(let c=0;c<BOARD_SIZE;c++){let r=0;while(r<BOARD_SIZE){const p=state.board[r][c];if(!p||p.kind!=='fruit'){r++;continue}let end=r+1;while(end<BOARD_SIZE&&state.board[end][c]&&state.board[end][c].kind==='fruit'&&state.board[end][c].type===p.type)end++;if(end-r>=3){for(let i=r;i<end;i++)matched.add(key(i,c));if(end-r>=5)earned++}r=end}}return{matched,earned}}
function adjacentBombs(matchSet){const out=[],seen=new Set();for(const k of matchSet){const[r,c]=coords(k);for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){if(!dr&&!dc)continue;const nr=r+dr,nc=c+dc,bk=key(nr,nc);if(!inside(nr,nc)||seen.has(bk))continue;const p=state.board[nr][nc];if(p&&p.kind==='bomb'){seen.add(bk);out.push([nr,nc])}}}return out}
function tileAt(r,c){return boardElement.querySelector(`.tile[data-row="${r}"][data-col="${c}"]`)}
function badge(x,y,text,cls='score-pop score-pop--fruit'){const b=document.createElement('div');b.className=cls;b.textContent=text;fx.appendChild(b);const a=b.animate([{transform:`translate(${x-38}px,${y-12}px) scale(.8)`,opacity:0},{transform:`translate(${x-38}px,${y-42}px) scale(1.06)`,opacity:1,offset:.3},{transform:`translate(${x-38}px,${y-92}px) scale(1)`,opacity:0}],{duration:850,easing:'cubic-bezier(0.18,0.84,0.32,1)',fill:'forwards'});a.onfinish=()=>b.remove()}
function badgeFor(keys,text,cls){const pts=[];for(const k of keys){const[r,c]=coords(k),t=tileAt(r,c);if(t){const q=t.getBoundingClientRect();pts.push([q.left+q.width/2,q.top+q.height/2])}}const box=boardElement.getBoundingClientRect(),x=pts.length?pts.reduce((s,p)=>s+p[0],0)/pts.length:box.left+box.width/2,y=pts.length?pts.reduce((s,p)=>s+p[1],0)/pts.length:box.top+box.height/2;badge(x,y,text,cls)}
function shake(n){if(!boardShell||!n||!boardShell.animate)return;const q=Math.min(4+n*1.5,10);boardShell.animate([{transform:'translate3d(0,0,0)'},{transform:`translate3d(${q}px,-2px,0)`},{transform:`translate3d(${-q}px,2px,0)`},{transform:`translate3d(${q*.7}px,0,0)`},{transform:'translate3d(0,0,0)'}],{duration:320,easing:'ease-out'})}
function buildClear(matchSet=new Set(),earned=0,initialBombs=[],combo=1){const cleared=new Set(matchSet),queue=[...initialBombs],queued=new Set(initialBombs.map(([r,c])=>key(r,c))),done=new Set();for(const b of adjacentBombs(matchSet)){const k=key(b[0],b[1]);if(!queued.has(k)){queued.add(k);queue.push(b)}}while(queue.length){const[br,bc]=queue.shift(),bk=key(br,bc),bomb=state.board[br]?.[bc];if(done.has(bk)||!bomb||bomb.kind!=='bomb')continue;done.add(bk);cleared.add(bk);for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){const nr=br+dr,nc=bc+dc,k=key(nr,nc);if(!inside(nr,nc))continue;const p=state.board[nr][nc];cleared.add(k);if(p&&p.kind==='bomb'&&!queued.has(k)){queued.add(k);queue.push([nr,nc])}}}
let fruits=0,bombs=0;for(const k of cleared){const[r,c]=coords(k),p=state.board[r][c];if(!p)continue;if(p.kind==='bomb')bombs++;else fruits++;state.board[r][c]=null}const total=fruits+bombs;if(earned)state.bombBank=Math.min(BOMB_BANK_MAX,state.bombBank+earned);if(total)addTime(1);const gain=(fruits*10+bombs*75+earned*50)*combo;state.score+=gain;state.bombsDetonated+=bombs;state.meter=Math.min(state.meterGoal,state.meter+fruits+bombs*12+earned*8+Math.max(combo-1,0)*2);if(state.meter>=state.meterGoal)state.pendingLevelUp=true;if(total){badgeFor(cleared,combo>1?`+${gain} x${combo}`:bombs?`+${gain} 💥`:`+${gain}`,bombs?'score-pop score-pop--bomb':'score-pop score-pop--fruit')}if(combo>1)badgeFor(cleared,`Combo x${combo}!`,'combo-pop');if(earned)badgeFor(cleared,`Bomb bank +${earned}!`,'combo-pop');shake(bombs);return total}
function collapse(){for(let c=0;c<BOARD_SIZE;c++){let w=BOARD_SIZE-1;for(let r=BOARD_SIZE-1;r>=0;r--){if(state.board[r][c]){state.board[w][c]=state.board[r][c];if(w!==r)state.board[r][c]=null;w--}}while(w>=0){state.board[w][c]=null;w--}}}
function refill(){for(let r=0;r<BOARD_SIZE;r++)for(let c=0;c<BOARD_SIZE;c++)if(!state.board[r][c])state.board[r][c]=randomFruit()}
function renderBoard(){boardElement.innerHTML='';for(let r=0;r<BOARD_SIZE;r++)for(let c=0;c<BOARD_SIZE;c++){const p=state.board[r][c],btn=document.createElement('button');btn.type='button';btn.dataset.row=String(r);btn.dataset.col=String(c);if(!p){btn.className='tile tile--empty';btn.disabled=true;btn.setAttribute('aria-hidden','true');boardElement.appendChild(btn);continue}btn.className=`tile tile--${p.kind==='bomb'?'bomb':p.type}`;btn.setAttribute('aria-label',p.kind==='bomb'?`Bomb at row ${r+1}, column ${c+1}`:`${LOOKUP[p.type].label} at row ${r+1}, column ${c+1}`);if(state.swipeStart&&state.swipeStart.row===r&&state.swipeStart.col===c)btn.classList.add('is-active');const inner=document.createElement('span');inner.className='tile-inner';const piece=document.createElement('span');piece.className='piece';piece.textContent=p.kind==='bomb'?'💣':LOOKUP[p.type].emoji;inner.appendChild(piece);btn.appendChild(inner);boardElement.appendChild(btn)}}
function renderHud(){const mt=`${state.meter} / ${state.meterGoal}`,pct=`${(state.meter/state.meterGoal)*100}%`;levelEl.textContent=String(state.level);timeEl.textContent=fmt(state.timeLeft);timerEl.classList.remove('is-warning','is-danger');if(state.timeLeft<=15)timerEl.classList.add('is-danger');else if(state.timeLeft<=30)timerEl.classList.add('is-warning');scoreEl.textContent=String(state.score);bombsEl.textContent=String(state.bombsDetonated);if(bankEl)bankEl.textContent=`${state.bombBank} / ${BOMB_BANK_MAX}`;if(bankBtn)bankBtn.disabled=state.bombBank<=0||state.busy||state.pendingLevelUp||state.timeExpired;meterEl.textContent=mt;meterFill.style.width=pct;meterTop.textContent=mt;meterTopFill.style.width=pct;const nf=nextFruit();hintEl.textContent=nf?`Level ${state.level}: ${state.availableFruits.length} fruit types active. Next unlock: ${nf.label} at level ${nf.unlockLevel}. Match 5 to bank bombs.`:'All current fruit are unlocked. Match 5 to keep banking bombs.'}
function renderAll(){renderBoard();renderHud()}
function hideOverlay(){state.overlayMode=null;overlay.classList.add('hidden')}
function showLevel(){state.overlayMode='level';clearTimer();const nf=nextFruit();overlayEyebrow.textContent='Level cleared';overlayTitle.textContent=`Level ${state.level+1}`;overlayText.textContent=nf&&nf.unlockLevel===state.level+1?`${nf.label} joins the board next. Your bomb bank carries forward.`:'Fresh board, tougher goal, and your banked bombs carry forward.';continueBtn.textContent='Keep Crushing';overlay.classList.remove('hidden')}
function showGameOver(){state.overlayMode='gameover';state.timeExpired=true;state.pendingLevelUp=false;clearTimer();state.busy=false;overlayEyebrow.textContent="Time's up";overlayTitle.textContent='Round Over';overlayText.textContent=`Final score: ${state.score}. You reached level ${state.level}. Tap below to jump back in.`;continueBtn.textContent='Play Again';overlay.classList.remove('hidden')}
async function resolveBoard(initial=null){let pending=initial,combo=1;while(true){let cleared=0;if(pending){cleared=buildClear(pending.matchSet||new Set(),pending.earnedBombs||0,pending.initialBombs||[],combo);pending=null}else{const{matched,earned}=scanMatches();if(!matched.size)break;cleared=buildClear(matched,earned,[],combo)}if(!cleared)break;renderAll();await wait(420);collapse();refill();renderAll();await wait(160);if(state.timeExpired||state.pendingLevelUp)break;combo++}state.busy=false;renderHud();if(state.timeExpired)showGameOver();else if(state.pendingLevelUp)showLevel()}
async function trySwap(fr,fc,tr,tc){if(!inside(tr,tc)||state.busy||state.pendingLevelUp||state.timeExpired||state.overlayMode==='gameover')return;state.busy=true;[state.board[fr][fc],state.board[tr][tc]]=[state.board[tr][tc],state.board[fr][fc]];renderBoard();await wait(120);const moved=[];for(const[r,c]of[[fr,fc],[tr,tc]]){const p=state.board[r][c];if(p&&p.kind==='bomb')moved.push([r,c])}if(moved.length){await resolveBoard({initialBombs:moved});return}const{matched,earned}=scanMatches();if(!matched.size){[state.board[fr][fc],state.board[tr][tc]]=[state.board[tr][tc],state.board[fr][fc]];renderBoard();await wait(120);penalty(INVALID_SWAP_PENALTY);state.busy=false;renderHud();return}await resolveBoard({matchSet:matched,earnedBombs:earned})}
function dropBankBomb(){if(state.busy||state.pendingLevelUp||state.timeExpired||state.bombBank<=0)return;const fruits=[];for(let r=0;r<BOARD_SIZE;r++)for(let c=0;c<BOARD_SIZE;c++){const p=state.board[r][c];if(p&&p.kind==='fruit')fruits.push([r,c])}if(!fruits.length)return;const[r,c]=fruits[Math.floor(Math.random()*fruits.length)];state.bombBank--;state.board[r][c]={kind:'bomb'};renderAll();const t=tileAt(r,c);if(t){const q=t.getBoundingClientRect();badge(q.left+q.width/2,q.top+q.height/2,'Bomb dropped!','combo-pop')}}
function startNewRun(){clearTimer();Object.assign(state,{level:1,score:0,bombsDetonated:0,bombBank:0,meter:0,meterGoal:LEVEL_GOAL_START,timeLeft:ROUND_TIME_SECONDS,busy:false,pendingLevelUp:false,timeExpired:false,overlayMode:null,swipeStart:null});state.availableFruits=activeFruits();state.board=makeBoard();hideOverlay();renderAll();startTimer(false)}
function advanceLevel(){if(state.timeExpired){showGameOver();return}state.level++;state.meterGoal=LEVEL_GOAL_START+(state.level-1)*LEVEL_GOAL_STEP;state.meter=0;state.pendingLevelUp=false;state.availableFruits=activeFruits();state.board=makeBoard();hideOverlay();renderAll();startTimer(true)}
function overlayAction(){if(state.overlayMode==='gameover')startNewRun();else if(state.overlayMode==='level')advanceLevel()}
function pointerDown(e){const tile=e.target.closest('.tile');if(!tile||state.busy||state.pendingLevelUp||state.timeExpired||tile.disabled)return;state.swipeStart={row:Number(tile.dataset.row),col:Number(tile.dataset.col),x:e.clientX,y:e.clientY,id:e.pointerId};if(boardElement.setPointerCapture)boardElement.setPointerCapture(e.pointerId);renderBoard()}
function releasePointer(id){if(boardElement.hasPointerCapture&&boardElement.hasPointerCapture(id))boardElement.releasePointerCapture(id)}
function pointerUp(e){if(!state.swipeStart||e.pointerId!==state.swipeStart.id)return;const{row,col,x,y}=state.swipeStart;releasePointer(e.pointerId);state.swipeStart=null;const dx=e.clientX-x,dy=e.clientY-y;renderBoard();if(Math.hypot(dx,dy)<SWIPE_THRESHOLD)return;let nr=row,nc=col;if(Math.abs(dx)>Math.abs(dy))nc+=dx>0?1:-1;else nr+=dy>0?1:-1;trySwap(row,col,nr,nc)}
function pointerCancel(e){if(!state.swipeStart||e.pointerId!==state.swipeStart.id)return;releasePointer(e.pointerId);state.swipeStart=null;renderBoard()}
boardElement.addEventListener('pointerdown',pointerDown);boardElement.addEventListener('pointerup',pointerUp);boardElement.addEventListener('pointercancel',pointerCancel);newBtn.addEventListener('click',startNewRun);continueBtn.addEventListener('click',overlayAction);if(bankBtn)bankBtn.addEventListener('click',dropBankBomb);startNewRun();